<?php
// O LOOP INFINITO É UM ERRO QUE PODE SER OCASIONADO QUANDO UMA ESTRUTURA DE REPETIÇÃO NÃO TEM UMA CONDIÇÃO DE TÉRMINO QUE SEJA POSSÍVEL.
// POR EXEMPLO: X > 10 E A VARIÁVEL DE REFERêNCIA TEM UM DECREMENTO, NÃO INCREMENTO.
// ISSO VAI FAZER O SOFTWARE TRAVAR, E PODE SER UM GRANDE PROBLEMA CASO USUÁRIOS ESTEJAM ACESSANDO O MESMO.


    for($i = 0; $i < 10; $i++){ // COM ESTE SINAL DE -- O LOOP SERÁ INFINITO

        echo "Teste <br>";
    }