<?php
// COMO ABORDADO NAS SEÇÕES INICIAIS, ESTA É UMA DAS PRINCIPAIS FUNCIONALIDADES DO PHP.
// PODEMOS INSERIR CÓDIGO DINÂMICO ENTRE NOSSAS TAGS.
// AS EXTENSÕES PARA ESTE TIPO DE ARQUIVO PODEM SER DE .PHP OU .PHTML

    $nome = "Luan";
    $produtos = ["Carro", "Avião", "Lancha"];

?>