<?php
// SÃO BLOCOS DE CÓDIGOS QUE POSSUEM NOMES.
// REALIZÃO UMA AÇÃO E PODEM SER REAPROVEITADAS (CHAMADAS NOVAMENTE) AO LONGO DO PROGRAMA.
// PODEMOS PASSAR PARÂMETROS PARA FUNÇÕES, QUE MOLDAM A SUA EXECUÇÃO.
// A CRIAÇÃO DE FUNÇÕES REDUZ A DUPLICIDADE DE CÓDIGO. E TBM MELHORA A MANUTENÇÃO DO MESMO.
// O PHP POSSUE DIVERSAS FUNÇÕES PRONTAS, QUE PODEMOS UTILIZAR.

    function teste(){

        // código

    }